### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ianmiell** [ers35/luakernel#2]
``` sh
                shutit.install('git')
                shutit.install('make')
                shutit.install('gcc')
                shutit.install('mlocate')
                shutit.install('libc6-dev-i386')
                shutit.install('lua5.2')
                shutit.send('updatedb')
                shutit.send('export CPATH=/usr/include/x86_64-linux-gnu:/usr/include')
                shutit.send('git clone https://github.com/ers35/luakernel.git')
                shutit.send('cd luakernel')
                shutit.send('make')
```

Running the above commands (with the shutit commands taken out) on docker ubuntu 14.04 I get this error:

```
./musl-custom-gcc -std=gnu99 -m64 -fno-PIC -nostdlib -nodefaultlibs -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -masm=intel -O1 -g -c init.S -o bin/initS.o
gcc -std=gnu99 -m64 -fno-PIC -nostdlib -nodefaultlibs -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -masm=intel -O1 -g -c -m32 init.c -o bin/init.o
objcopy -I elf32-i386 -O elf64-x86-64 bin/init.o bin/init.o
./generate-lua-bundle.sh
./musl-custom-gcc -std=gnu99 -m64 -fno-PIC -nostdlib -nodefaultlibs -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -masm=intel -O1 -g -c -Idep/lua-5.2.3/src -Idep/sqlite3 luakernel.c -fno-stack-protector -o bin/luakernel.o
In file included from /usr/include/libio.h:31:0,
                 from /usr/include/stdio.h:74,
                 from luakernel.c:3:
/usr/include/_G_config.h:46:20: error: unknown type name '__gnuc_va_list'
 #define _G_va_list __gnuc_va_list
                    ^
/usr/include/libio.h:44:21: note: in expansion of macro '_G_va_list'
 #define _IO_va_list _G_va_list
                     ^
/usr/include/libio.h:465:4: note: in expansion of macro '_IO_va_list'
    _IO_va_list, int *__restrict);
    ^
...
```

Tried fiddling with err.h includes with no success.

**Comment by ers35** [comment]
Install [gcc-multilib](http://packages.ubuntu.com/trusty/gcc-multilib) and [xorriso](http://packages.ubuntu.com/trusty/xorriso).

**Comment by ianmiell** [comment]
Thanks - get this error now:

```
./musl-custom-gcc -std=gnu99 -m64 -fno-PIC -nostdlib -nodefaultlibs
-fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -masm=intel -O1
-g -c -Idep/lua-5.2.3/src -Idep/sqlite3 luakernel.c -fno-stack-protector -o
bin/luakernel.o
In file included from /usr/include/libio.h:31:0,
                 from /usr/include/stdio.h:74,
                 from luakernel.c:3:
/usr/include/_G_config.h:46:20: error: unknown type name '__gnuc_va_list'
 #define _G_va_list __gnuc_va_list
                    ^
/usr/include/libio.h:44:21: note: in expansion of macro '_G_va_list'
 #define _IO_va_list _G_va_list
                     ^
/usr/include/libio.h:465:4: note: in expansion of macro '_IO_va_list'
    _IO_va_list, int *__restrict);
    ^
/usr/include/_G_config.h:46:20: error: unknown type name '__gnuc_va_list'
```

Commands are now:

```
            shutit.install('git')
            shutit.install('make')
            shutit.install('gcc')
            shutit.install('libc6-dev-i386')
            shutit.install('gcc-multilib')
            shutit.install('xorriso')
            shutit.install('lua5.2')
            shutit.send('export
```

CPATH=/usr/include/x86_64-linux-gnu:/usr/include')
                shutit.send('git clone
https://github.com/ers35/luakernel.git')
                shutit.send('cd luakernel')
                shutit.send('make')

On 21 October 2014 23:26, Eric R. Schulz notifications@github.com wrote:

> Install gcc-multilib http://packages.ubuntu.com/trusty/gcc-multilib and
> xorriso http://packages.ubuntu.com/trusty/xorriso.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ers35/luakernel/issues/2#issuecomment-60009285.

## 

http://www.openbet.com/Ian MiellHead of DevOpsT:+44 208 742 1600

+44 208 987 1129M:+44 793 150
7458E:ian.miell@openbet.comW:www.openbet.comOpenBet
Ltd
Chiswick Park Building 9
566 Chiswick High Rd
London
W4 5XT http://twitter.com/OpenBet_Ltd
http://www.linkedin.com/company/165331/
http://www.facebook.com/OpenBetWinner
of Sports Betting Supplier of the Year at the EGR B2B Awards 2010, 2011 &
2012This message is confidential and intended only for the addressee. If
you have received this message in error, please immediately notify the
postmaster@openbet.com and delete it from your system as well as any
copies. The content of e-mails as well as traffic data may be monitored by
OpenBet for employment and security purposes. To protect the environment
please do not print this e-mail unless necessary. OpenBet Ltd. Registered
Office: Chiswick Park Building 9, 566 Chiswick High Road, London, W4 5XT,
United Kingdom. A company registered in England and Wales. Registered no.
3134634. VAT no. GB927523612

**Comment by ianmiell** [comment]
I think I've fixed this - will upload later.

On 22 October 2014 07:35, Ian Miell ian.miell@openbet.com wrote:

> Thanks - get this error now:
> 
> ```
> ./musl-custom-gcc -std=gnu99 -m64 -fno-PIC -nostdlib -nodefaultlibs
> -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -masm=intel -O1
> -g -c -Idep/lua-5.2.3/src -Idep/sqlite3 luakernel.c -fno-stack-protector -o
> bin/luakernel.o
> In file included from /usr/include/libio.h:31:0,
>                  from /usr/include/stdio.h:74,
>                  from luakernel.c:3:
> /usr/include/_G_config.h:46:20: error: unknown type name '__gnuc_va_list'
>  #define _G_va_list __gnuc_va_list
>                     ^
> /usr/include/libio.h:44:21: note: in expansion of macro '_G_va_list'
>  #define _IO_va_list _G_va_list
>                      ^
> /usr/include/libio.h:465:4: note: in expansion of macro '_IO_va_list'
>     _IO_va_list, int *__restrict);
>     ^
> /usr/include/_G_config.h:46:20: error: unknown type name '__gnuc_va_list'
> ```
> 
> Commands are now:
> 
> ```
>             shutit.install('git')
>             shutit.install('make')
>             shutit.install('gcc')
>             shutit.install('libc6-dev-i386')
>             shutit.install('gcc-multilib')
>             shutit.install('xorriso')
>             shutit.install('lua5.2')
>             shutit.send('export
> ```
> 
> CPATH=/usr/include/x86_64-linux-gnu:/usr/include')
>                 shutit.send('git clone
> https://github.com/ers35/luakernel.git')
>                 shutit.send('cd luakernel')
>                 shutit.send('make')
> 
> On 21 October 2014 23:26, Eric R. Schulz notifications@github.com wrote:
> 
> > Install gcc-multilib http://packages.ubuntu.com/trusty/gcc-multilib
> > and xorriso http://packages.ubuntu.com/trusty/xorriso.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ers35/luakernel/issues/2#issuecomment-60009285.
> 
> ## 
> 
> http://www.openbet.com/Ian MiellHead of DevOpsT:+44 208 742 1600
> 
> +44 208 987 1129M:+44 793 150 7458E:ian.miell@openbet.comW:www.openbet.comOpenBet
> Ltd
> Chiswick Park Building 9
> 566 Chiswick High Rd
> London
> W4 5XT http://twitter.com/OpenBet_Ltd
> http://www.linkedin.com/company/165331/
> http://www.facebook.com/OpenBetWinner of Sports Betting Supplier of the
> Year at the EGR B2B Awards 2010, 2011 & 2012This message is confidential
> and intended only for the addressee. If you have received this message in
> error, please immediately notify the postmaster@openbet.com and delete it
> from your system as well as any copies. The content of e-mails as well as
> traffic data may be monitored by OpenBet for employment and security
> purposes. To protect the environment please do not print this e-mail unless
> necessary. OpenBet Ltd. Registered Office: Chiswick Park Building 9, 566
> Chiswick High Road, London, W4 5XT, United Kingdom. A company registered in
> England and Wales. Registered no. 3134634. VAT no. GB927523612

## 

http://www.openbet.com/Ian MiellHead of DevOpsT:+44 208 742 1600

+44 208 987 1129M:+44 793 150
7458E:ian.miell@openbet.comW:www.openbet.comOpenBet
Ltd
Chiswick Park Building 9
566 Chiswick High Rd
London
W4 5XT http://twitter.com/OpenBet_Ltd
http://www.linkedin.com/company/165331/
http://www.facebook.com/OpenBetWinner
of Sports Betting Supplier of the Year at the EGR B2B Awards 2010, 2011 &
2012This message is confidential and intended only for the addressee. If
you have received this message in error, please immediately notify the
postmaster@openbet.com and delete it from your system as well as any
copies. The content of e-mails as well as traffic data may be monitored by
OpenBet for employment and security purposes. To protect the environment
please do not print this e-mail unless necessary. OpenBet Ltd. Registered
Office: Chiswick Park Building 9, 566 Chiswick High Road, London, W4 5XT,
United Kingdom. A company registered in England and Wales. Registered no.
3134634. VAT no. GB927523612
